---
output: 
  officedown::rdocx_document:
    reference_docx: ../styling/doc_template.docx
    tables:
      style: Table Grid
      layout: autofit
      width: 1.0
      conditional:
       first_row: true
       first_column: false
       last_row: false
       last_column: false
       no_hband: false
       no_vband: true
    # lists:
    #   ol.style: 'Number alignment: Left'
    #   ul.style: List Paragraph
    page_margins:
      bottom: 1
      top: 1
      right: 0.8
      left: 0.8
      header: 0
      footer: 0
      gutter: 0
params:
  is_la_report: false
  school_name: 'Test school academy'
  term: 'Autumn 2024'
bibliography: ../styling/references.bib
csl: ../styling/the-lancet.csl
nocite: '@*'
execute:
  enabled: true
---

```{r, echo = FALSE}
#| echo: false

school_name <- params$school_name
is_la_report <- params$is_la_report
term <- params$term
```


```{r front-page, echo=FALSE, results='asis'}
cat(knitr::knit_child('front-cover.qmd', envir = environment(), quiet = TRUE))
```

\newpage

```{r introduction, echo=FALSE, results='asis'}
cat(knitr::knit_child('introduction.qmd', envir = environment(), quiet = TRUE))
```

\newpage

# School survey results

## School survey response {.numbered}

Pupils in your school completed the survey `r date_range(input_data)`.



```{r}

```

\newpage

```{r outtro, echo=FALSE, results='asis'}
cat(knitr::knit_child('outtro.qmd', envir = environment(), quiet = TRUE))
```

\newpage

# References
