#' cleanUpload UI
#'
#' @param id Unique id for module instance.
#'
#' @keywords internal
cleanUploadUI <- function(id, multiple = TRUE){
	ns <- NS(id)

	tagList(
		h2("Upload cleaned data"),
		fileInput(ns("upload"),
		          label = span("Select cleaned data Excel spreadsheet",
		                       bslib::tooltip(
		                         icon("info-circle"),
		                         "The data should be in the `.xlsx` format generated by the data cleaning tab.",
		                         placement = "right",)
		          ),
		          multiple = multiple,
		          buttonLabel = "Upload...",
		          width = "100%",
		          accept = ".xlsx"),
		verbatimTextOutput(ns("test")),
		uiOutput(ns("warn"))
	)
}

#' cleanUpload Server
#'
#' @param id Unique id for module instance.
#'
#' @keywords internal
cleanUpload_server <- function(id){
	moduleServer(
		id,
		function(
			input,
			output,
			session
			){

				ns <- session$ns
				send_message <- make_send_message(session)

				# create an empty df to hold warning messages
				checks <- reactiveValues(checks = data.frame(message = character(0),
				                                             level = integer(0)))

				# get uploaded data

				clean_data_list <- reactive({
				  req(input$upload)
				  purrr::map(input$upload$datapath, ~openxlsx::read.xlsx(.x, sheet = 1, sep.names = " "))
				})

				# stack dataframes if multiple uploaded

				uploaded_data <- reactive({
				  if (length(clean_data_list()) == 1) {
				    return(clean_data_list()[[1]])
				  }
				  if (length(clean_data_list()) > 1) {
				    if (!all(purrr::map_lgl(clean_data_list(),
				                           ~identical(colnames(.x),
				                                      colnames(clean_data_list()[[1]]))
				                           ))) {
				      error_message <- data.frame(message = c("Column names do not match"),
				                                  level = c(3))

				      isolate({checks$checks <- error_message})
				      return(NULL)
				    } else {
				      return(purrr::reduce(clean_data_list(), .f = dplyr::bind_rows))
				    }
				  }
				})

				# filter out excluded observations

				filtered_data <- reactive({
				  req(uploaded_data())
				  if (!"Keep row?" %in% colnames(uploaded_data())) {
				    error_message <- data.frame(message = c("Data does not contain 'Keep row?' column"),
				                                  level = c(3))

				    isolate({checks$checks <- error_message})
				    return(NULL)
				  } else {
				    uploaded_data() |>
				      dplyr::filter(`Keep row?` == 1) |>
				      dplyr::select(-c("Keep row?", "Error messages", "Reviewer notes"))
				  }

				})


				# create warning ui
				output$warn <- renderUI({

				  req(clean_data_list, cancelOutput = TRUE)

				  if (!is.null(filtered_data())) {
				    checks$checks <- upload_checks_clean(filtered_data(), vars = NULL)
				  }

				  warnings <- purrr::pmap(checks$checks,
				                          make_upload_warning)

				  do.call(tagList, warnings)

				})

				return(filtered_data)

		}
	)
}

# UI
# cleanUploadUI('id')

# server
# cleanUpload_server('id')
