#' cleanUpload UI
#'
#' @param id Unique id for module instance.
#'
#' @keywords internal
cleanUploadUI <- function(id, multiple = TRUE){
	ns <- NS(id)

	tagList(
		h2("Upload cleaned data"),
		fileInput(ns("upload"),
		          label = span("Select cleaned data Excel spreadsheet",
		                       bslib::tooltip(
		                         icon("info-circle"),
		                         "The data should be in the `.xlsx` format generated by the data cleaning tab.",
		                         placement = "right",)
		          ),
		          multiple = multiple,
		          buttonLabel = "Upload...",
		          width = "100%",
		          accept = ".xlsx"),
		verbatimTextOutput(ns("test")),
		uiOutput(ns("warn"))
	)
}

#' cleanUpload Server
#'
#' @param id Unique id for module instance.
#'
#' @keywords internal
cleanUpload_server <- function(id){
	moduleServer(
		id,
		function(
			input,
			output,
			session
			){

				ns <- session$ns
				send_message <- make_send_message(session)

				# create warnings
				# create an empty df to hold warning messages
				checks <- reactiveValues(checks = data.frame(fail = logical(0),
				                                             message = character(0),
				                                             level = integer(0)))


				# upload data
				clean_data_list <- reactive({
				  req(input$upload)
				  purrr::map(input$upload$datapath, ~openxlsx::read.xlsx(.x, sheet = 1))
				})

				clean_data <- reactive({
				  if(length(clean_data_list()) == 1){
				    return(clean_data_list()[[1]])
				  }
				  if (length(clean_data_list()) > 1){
				    if(!all(purrr::map_lgl(clean_data_list(),
				                           ~identical(colnames(.x),
				                                      colnames(clean_data_list()[[1]]))
				                           ))){
				      warning <- data.frame(fail = c(TRUE),
				                            message = c("Column names do not match"),
				                            level = c(3))

				      checks$checks <- warning

				      warning("hmmm")
				      return(NULL)
				    } else {
				      return(purrr::reduce(clean_data_list(), dplyr::bind_rows()))
				    }
				  }
				})

				# test output df

				output$test <- renderPrint({
				  head(clean_data())
				})

				# create warning ui
				output$warn <- renderUI({

				  req(nrow(checks$checks) > 0 , cancelOutput = TRUE)

				  warnings <- purrr::pmap(checks$checks[checks$checks$fail, c("message", "level")],
				                          make_upload_warning)

				  do.call(tagList, warnings)

				})

		}
	)
}

# UI
# cleanUploadUI('id')

# server
# cleanUpload_server('id')
